services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/be.dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./backend:/backend
    command: uvicorn website.asgi:application --host 0.0.0.0 --port 8000

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/fe.dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

networks:
  backend:
